name: GitHub CI
on:
  pull_request:
    # closed: removed since it might cancel the run related to merge on main
    # --> skip doc-deploy-pr
    # types: [opened, reopened, synchronize, edited, labeled, closed]
    types: [opened, reopened, synchronize, edited, labeled]
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

env:
  MAIN_PYTHON_VERSION: '3.10'
  DOCUMENTATION_CNAME: 'guitools.scade.docs.pyansys.com'
  LIBRARY_NAME: 'ansys-scade-guitools'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pr-name:
    name: "Check PR title"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    steps:
      - name: "Check commit name"
        uses: ansys/actions/check-pr-title@v10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: ansys/actions/code-style@v10
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  doc-style:
    name: "Documentation style"
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: ansys/actions/doc-style@v10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  update-changelog:
    name: "Update CHANGELOG (on release)"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags') && github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: ansys/actions/doc-deploy-changelog@v10
        with:
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  build-wheelhouse:
    name: "Build wheelhouse for supported Python version"
    runs-on: ${{ matrix.os }}
    if: github.event.action != 'closed'
    needs: [code-style]
    permissions:
      contents: read
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
      - uses: ansys/actions/build-wheelhouse@v10
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          attest-provenance: true

  tests:
    name: "Unit tests"
    runs-on: [self-hosted, 'SCADE']
    needs: [build-wheelhouse]
    strategy:
      matrix:
        os: [windows-latest]
        scade-version: ['25.2']
      fail-fast: false
    steps:
      - name: "Install Git and clone project"
        uses: actions/checkout@v6

      - uses: ansys/scade-actions/scade-tests-pytest@v2
        with:
          checkout: false
          scade-version: ${{ matrix.scade-version }}

      - name: "Upload coverage reports to Codecov"
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ansys/scade-variants
          files: .cov/xml

  doc-build:
    name: "Build documentation"
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    timeout-minutes: 30
    needs: [doc-style]
    steps:
      - uses: ansys/actions/doc-build@v10
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Zipping the examples directory"
        run: |
          sudo apt-get install zip
          zip -r examples.zip ./examples

      - name: "Upload zip to artifacts"
        uses: actions/upload-artifact@v6
        with:
          name: examples
          path: ./examples.zip
          retention-days: 7
          if-no-files-found: error

  # temporary deployments are not deleted
  # doc-deploy-pr:
  #   name: "Deploy PR documentation"
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #   needs: doc-build
  #   # Run when the PR is closed i.e. when doc-build job is skipped
  #   # Also run only when appropriate label is added
  #   if: |
  #     always() &&
  #     (needs.doc-build.result == 'success' || needs.doc-build.result == 'skipped') &&
  #     contains(github.event.pull_request.labels.*.name, 'deploy-pr-doc')
  #   steps:
  #     - uses: ansys/actions/doc-deploy-pr@main
  #       with:
  #         cname: ${{ env.DOCUMENTATION_CNAME }}
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
  #         bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
  #         maximum-pr-doc-deployments: 5

  build-library:
    name: "Build library basic example"
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    needs: [tests, doc-build]
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - uses: ansys/actions/build-library@v10
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          attest-provenance: true

  release:
    name: "Release project"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags') && github.event.action != 'closed'
    runs-on: ubuntu-latest
    needs: [build-library, update-changelog]
    permissions:
      id-token: write
      contents: write
    steps:

      - name: "Download the library artifacts from build-library step"
        uses: actions/download-artifact@v7
        with:
          name: ${{ env.LIBRARY_NAME }}-artifacts
          path: ${{ env.LIBRARY_NAME }}-artifacts

      - name: "Display structure of downloaded files"
        run: ls -Rla

      - name: "Upload artifacts to PyPI using trusted publisher"
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          repository-url: "https://upload.pypi.org/legacy/"
          print-hash: true
          packages-dir: ${{ env.LIBRARY_NAME }}-artifacts
          skip-existing: false

      - name: "Release to GitHub"
        uses: ansys/actions/release-github@v10
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          additional-artifacts: 'examples'
          token: ${{ secrets.GITHUB_TOKEN }}

  doc-deploy-dev:
    name: "Deploy development documentation"
    # Deploy development only when merging or pushing to the 'main' branch
    runs-on: ubuntu-latest
    needs: [build-library]
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags') && github.event.action != 'closed'
    steps:
      - uses: ansys/actions/doc-deploy-dev@v10
        with:
          doc-artifact-name: 'documentation-html'
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  doc-deploy-stable:
    name: "Deploy stable documentation"
    # Deploy release documentation when creating a new tag
    runs-on: ubuntu-latest
    needs: [release]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags') && github.event.action != 'closed'
    steps:
      - uses: ansys/actions/doc-deploy-stable@v10
        with:
          doc-artifact-name: 'documentation-html'
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
